# Generated by Django 6.0.6 on 2026-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private profile'),
        ),
    ]
